update term set name_fr = 'Till d''hébergement' where id =13569;
update term set name_fr = 'Granulats légers' where id =13594;
update term set name_fr = 'Granulats lourds' where id =14121;
update term set name_fr = 'Essais radiométriques' where id =14176;
update term set name_fr = 'Césium' where id =14178;
update term set name_fr = 'Géochimie du césium' where id =14179;
update term set name_fr = 'Dungannonite' where id =14180;
update term set name_fr = 'Dépôts éoliens' where id =14181;
update term set name_fr = 'Méthode Glaciofocus' where id =14182;
update term set name_fr = 'Gaz naturel' where id =14183;
update term set name_fr = 'Flotteur' where id =14184;
update term set name_fr = 'Dépôts fluvioglaciaires' where id =14185;
update term set name_fr = 'Dépôts fluvioglaciaires' where id =14186;
update term set name_fr = 'Dépôts fluvioglaciaires' where id =14187;
update term set name_fr = 'Eau souterraine' where id =14188;
update term set name_fr = 'Lixiviation en tas' where id =14189;
update term set name_fr = 'Champs de glace' where id =14190;
update term set name_fr = 'Pelletisation' where id =14191;
update term set name_fr = 'Calcaires cristallins' where id =14192;
update term set name_fr = 'Linéaments structuraux' where id =14193;
update term set name_fr = 'Lollingite' where id =14194;
update term set name_fr = 'Barrières' where id =14195;
update term set name_fr = 'Corps minéralisés' where id =14196;
update term set name_fr = 'Gisements de minerai' where id =14197;
update term set name_fr = 'Minéralisation primaire' where id =14198;
update term set name_fr = 'Minéralisation secondaire' where id =14199;
update term set name_fr = 'Claims' where id =14200;
update term set name_fr = 'Colombium' where id =14201;
update term set name_fr = 'Géochimie du Columbium' where id =14202;
update term set name_fr = 'Genèse du minerai' where id =14203;
update term set name_fr = 'Mousse de tourbe' where id =14204;
update term set name_fr = 'Pressions des fluides interstitiels' where id =14205;
update term set name_fr = 'Ondes de Rayleigh' where id =14206;
update term set name_fr = 'Détermination de l''âge isotopique' where id =14207;
update term set name_fr = 'Salinité de l''eau' where id =14208;
update term set name_fr = 'Caractéristiques sédimentaires' where id =14209;
update term set name_fr = 'Programmes informatiques' where id =14210;
update term set name_fr = 'Charge de lavage' where id =14211;
update term set name_fr = 'Sources chaudes' where id =14212;
update term set name_fr = 'Courants du fond de la mer' where id =14213;
update term set name_fr = 'Morphologie, fossile' where id =14214;
update term set name_fr = 'Oolithes' where id =14215;
update term set name_fr = 'Levés électromagnétiques' where id =14216;
update term set name_fr = 'Diagraphies de puits, Gamma' where id =14217;
update term set name_fr = 'Transmissibilité' where id =14218;
update term set name_fr = 'Bojite' where id =14219;
update term set name_fr = 'Stockage des carottes de forage' where id =14220;
update term set name_fr = 'Caractéristiques fluvioglaciaires' where id =14221;
update term set name_fr = 'Caractéristiques fluvioglaciaires' where id =14222;
update term set name_fr = 'Planification du développement des ressources' where id =14223;
update term set name_fr = 'Pentes d''éboulis' where id =14224;
update term set name_fr = 'Géochimie sédimentaire' where id =14225;
update term set name_fr = 'Hydrates de gaz' where id =14226;
update term set name_fr = 'Eaux de réservoir' where id =14227;
update term set name_fr = 'Turbidité Structures des courants' where id =14228;
update term set name_fr = 'SONDAGE À LA TARIÈRE' where id =14229;
update term set name_fr = 'Trous de forage à la tarière' where id =14230;
update term set name_fr = 'Trous de forage au diamant' where id =14231;
update term set name_fr = 'Trous de forage' where id =14232;
update term set name_fr = 'Analyses de la qualité de l''eau' where id =14233;
update term set name_fr = 'Tests de qualité de l''eau' where id =14234;
