# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 'DSpace Java Build'
variables:
  - name: app
    value: 'DSpaceJava'
  - name: build_id
    value: $(Build.BuildId)

trigger:
  branches:
    include:
      - main
      - oir-dev

stages:
  - stage: DSPACE_CI
    displayName: 'Build DSpace container image'
    #    condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    #    variables:
    #    - group: DSpace_Postgresql_Credentials
    jobs:
      - job: build_backend
        timeoutInMinutes: 20
        pool:
            name: Apption Pool
            demands:
                - Agent.OS -equals Windows_NT
                - Agent.Name -equals WIN10-BUILD
        steps:
          - task: Docker@2
            displayName: 'Build and Push an image'
            inputs:
              command: 'buildAndPush'
              dockerfile: 'Dockerfile'
              repository: 'dspace-backend'
              containerRegistry: 'stevedspaceregistry'
              tags: |
                $(Build.BuildId)
                latest
            condition: succeededOrFailed()